name: ccompile
version: 0.1.8
author: Andrew Mezoni <andrew.mezoni@gmail.com>
homepage: https://github.com/mezoni/ccompile
description: >
  Library for compiling C/C++ source files from Dart scripts.
  The main purpose of compiling native extensions from Dart source files.
  It is also possible to use this to compile any other small projects.
dependencies:
  args:
    sdk: args